[build]
  base = "client"
  command = "yarn build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://proptic-api-production.up.railway.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
