[build]
  base = "client"  # since your Next.js app is in client folder
  publish = "client/.next"  # Netlify needs the full path
  command = "cd client && npm run build"

[build.environment]
  # Add any environment variables you need
  NEXT_PUBLIC_API_URL = "proptic-api-production.up.railway.app"

# REQUIRED: Netlify Next.js plugin for SSR support
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Redirects for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200