[build]
builder = "dockerfile" 

# Frontend service
[services.frontend]
builder = "dockerfile"
rootDirectory = "client"

# Backend service
[services.backend]
builder = "dockerfile"
rootDirectory = "services/properties" 