# Root config (optional)
[build]
builder = "dockerfile"

# Frontend service
[services.frontend]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
rootDirectory = "client"

# Backend service
[services.backend]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
rootDirectory = "services/properties"
