services:
  - name: proptic-api
    type: web
    runtime: docker
    plan: free
    buildContext: ./services
    dockerfilePath: ./services/properties/Dockerfile  # Add full path

    
    envVars:
      - key: PORT
        value: 9000
      - key: DJANGO_SETTINGS_MODULE
        value: "properties.settings"
      - key: DATABASE_URL
        fromDatabase:
          name: proptic-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "proptic-api.onrender.com,localhost,127.0.0.1"

  - name: proptic-client
    type: web
    runtime: docker
    plan: free
    buildContext: ./client
    dockerfilePath: ./client/Dockerfile
    buildCommand: pnpm install; pnpm build
    startCommand: pnpm start

    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: "https://proptic-api.onrender.com"
        
      - key: NODE_ENV
        value: "production"

      - key: PORT
        value: 3000

databases:
  - name: proptic-db
    databaseName: proptic_demo_db
    user: proptic_db_admin
    plan: free