# Generated by Django 5.2.1 on 2025-05-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propertyproject',
            table='core_property_projects',
        ),
        migrations.AlterModelTable(
            name='propertyunit',
            table='core_property_units',
        ),
        migrations.AlterModelTable(
            name='role',
            table='core_roles',
        ),
        migrations.AlterModelTable(
            name='tenantprofile',
            table='core_tenant_profiles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_users',
        ),
    ]
