# Generated by Django 5.2.1 on 2025-05-29 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyunit',
            old_name='paid',
            new_name='is_listed_for_rent',
        ),
        migrations.RenameField(
            model_name='propertyunit',
            old_name='unit_number',
            new_name='unit_name',
        ),
        migrations.RemoveField(
            model_name='propertyunit',
            name='available',
        ),
        migrations.RemoveField(
            model_name='propertyunit',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='propertyunit',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='propertyunit',
            name='paid_days',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='property_unit',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='tenancy_end_date',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='tenancy_start_date',
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='is_listed_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_profiles/'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booking_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.propertyunit')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='core.propertyunit')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenancy_start_date', models.DateField()),
                ('tenancy_end_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rent_period_paid', models.PositiveIntegerField(default=0, help_text='Number of days covered by the paid rent')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='core.propertyunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenancies',
            },
        ),
    ]
