# Generated by Django 5.2.1 on 2025-05-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_propertyproject_table_alter_propertyunit_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propertyproject',
            table='property_projects',
        ),
        migrations.AlterModelTable(
            name='propertyunit',
            table='property_units',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='tenantprofile',
            table='tenant_profiles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
