# Generated by Django 5.2.1 on 2025-05-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_paid_propertyunit_is_listed_for_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyproject',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='property_projects/covers/'),
        ),
        migrations.CreateModel(
            name='PropertyUnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_units/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.propertyunit')),
            ],
            options={
                'db_table': 'property_unit_images',
                'constraints': [models.UniqueConstraint(fields=('property_unit', 'image'), name='unique_image_per_unit')],
            },
        ),
    ]
