# Generated by Django 5.2.1 on 2025-05-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_propertyproject_cover_photo_propertyunitimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest',
            new_name='guest_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='property_unit',
            new_name='property_unit_id',
        ),
        migrations.RenameField(
            model_name='propertyunit',
            old_name='property_project',
            new_name='property_project_id',
        ),
        migrations.RenameField(
            model_name='propertyunitimage',
            old_name='property_unit',
            new_name='property_unit_id',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='buyer',
            new_name='buyer_id',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='property_unit',
            new_name='property_unit_id',
        ),
        migrations.RenameField(
            model_name='tenancy',
            old_name='property_unit',
            new_name='property_unit_id',
        ),
        migrations.RenameField(
            model_name='tenancy',
            old_name='tenant',
            new_name='tenant_id',
        ),
        migrations.RenameField(
            model_name='tenantprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
