# Generated by Django 5.2.1 on 2025-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_guest_booking_guest_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertyunitimage',
            name='unique_image_per_unit',
        ),
        migrations.AddConstraint(
            model_name='propertyunitimage',
            constraint=models.UniqueConstraint(fields=('property_unit_id', 'image'), name='unique_image_per_unit'),
        ),
    ]
