# Generated by Django 5.2.1 on 2025-06-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_propertyunitimage_unique_image_per_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_id',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='propertyunit',
            old_name='property_project_id',
            new_name='property_project',
        ),
        migrations.RenameField(
            model_name='propertyunitimage',
            old_name='property_unit_id',
            new_name='property_unit',
        ),
        migrations.RenameField(
            model_name='tenancy',
            old_name='property_unit_id',
            new_name='property_unit',
        ),
        migrations.RenameField(
            model_name='tenancy',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='tenantprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
