# Generated by Django 5.2.1 on 2025-06-02 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_guest_id_booking_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='property_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.propertyproject'),
        ),
    ]
