# Generated by Django 5.2.1 on 2025-06-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_is_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='description',
            new_name='display_name',
        ),
    ]
