# Generated by Django 5.2.2 on 2025-06-04 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_description_role_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenancy',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='rent_period_paid',
        ),
        migrations.CreateModel(
            name='RentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(default='completed', max_length=20)),
                ('rent_period_start_date', models.DateField()),
                ('rent_period_end_date', models.DateField()),
                ('paid_days', models.PositiveIntegerField(help_text='Number of days covered by this payment')),
                ('description', models.TextField(blank=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.tenancy')),
            ],
            options={
                'db_table': 'rent_transactions',
            },
        ),
    ]
